import * as os from 'os';
import { tplant } from '../src/tplant';

describe('Test commander options', () => {

    it('generate PlantUML with only Interfaces for Playground/Inheritance/autos.ts', () => {
        expect(tplant.convertToPlant(tplant.generateDocumentation(['test/Playground/Inheritance/autos.ts']), { associations: false, onlyInterfaces: true, onlyClasses: false }))
            .toEqual(
                ['@startuml',
                    'interface IVehicle {',
                    '    +start(type: string): string',
                    '}',
                    'interface ITrunk {',
                    '    +openTrunk(): void',
                    '}',
                    'interface IWindow {',
                    '    +openWindow(): void',
                    '}',
                    '@enduml'].join(os.EOL));
    });

    it('generate PlantUML for RayTracer with associations', () => {
        expect(tplant.convertToPlant(tplant.generateDocumentation(['test/Playground/RayTracer/index.ts']), { associations: true, onlyInterfaces: false, onlyClasses: false }))
            .toEqual(
                ['@startuml',
                    'class Vector {',
                    '    +x: number',
                    '    +y: number',
                    '    +z: number',
                    '    +{static} times(k: number, v: Vector): Vector',
                    '    +{static} minus(v1: Vector, v2: Vector): Vector',
                    '    +{static} plus(v1: Vector, v2: Vector): Vector',
                    '    +{static} dot(v1: Vector, v2: Vector): number',
                    '    +{static} mag(v: Vector): number',
                    '    +{static} norm(v: Vector): Vector',
                    '    +{static} cross(v1: Vector, v2: Vector): Vector',
                    '}',
                    'interface Ray {',
                    '    +start: Vector',
                    '    +dir: Vector',
                    '}',
                    'interface Intersection {',
                    '    +thing: Thing',
                    '    +ray: Ray',
                    '    +dist: number',
                    '}',
                    'class Color {',
                    '    +r: number',
                    '    +g: number',
                    '    +b: number',
                    '    +{static} scale(k: number, v: Color): Color',
                    '    +{static} plus(v1: Color, v2: Color): Color',
                    '    +{static} times(v1: Color, v2: Color): Color',
                    '    +{static} white: Color',
                    '    +{static} grey: Color',
                    '    +{static} black: Color',
                    '    +{static} background: Color',
                    '    +{static} defaultColor: Color',
                    '    +{static} toDrawingColor(c: Color): { r: number; g: number; b: number; }',
                    '}',
                    'interface Surface {',
                    '    +diffuse: (pos: Vector) => Color',
                    '    +specular: (pos: Vector) => Color',
                    '    +reflect: (pos: Vector) => number',
                    '    +roughness: number',
                    '}',
                    'interface Thing {',
                    '    +intersect: (ray: Ray) => Intersection',
                    '    +normal: (pos: Vector) => Vector',
                    '    +surface: Surface',
                    '    +destroy(): void',
                    '    +destroy(name: string): void',
                    '}',
                    'interface Light {',
                    '    +pos: Vector',
                    '    +color: Color',
                    '}',
                    'class Camera {',
                    '    +forward: Vector',
                    '    +right: Vector',
                    '    +up: Vector',
                    '    +pos: Vector',
                    '}',
                    'interface Scene {',
                    '    +things: Thing[]',
                    '    +lights: Light[]',
                    '    +camera: Camera',
                    '}',
                    'class Plane implements Thing {',
                    '    +normal: (pos: Vector) => Vector',
                    '    +intersect: (ray: Ray) => Intersection',
                    '    +surface: Surface',
                    '}',
                    'class Sphere implements Thing {',
                    '    +radius2: number',
                    '    +center: Vector',
                    '    +surface: Surface',
                    '    +normal(pos: Vector): Vector',
                    '    +intersect(ray: Ray): { thing: this; ray: Ray; dist: number; }',
                    '}',
                    'namespace Surfaces {',
                    '}',
                    'class RayTracer {',
                    '    -maxDepth: number',
                    '    -intersections(ray: Ray, scene: Scene): Intersection',
                    '    -testRay(ray: Ray, scene: Scene): number',
                    '    -traceRay(ray: Ray, scene: Scene, depth: number): Color',
                    '    -shade(isect: Intersection, scene: Scene, depth: number): Color',
                    '    -getReflectionColor(thing: Thing, pos: Vector, normal: Vector, rd: Vector, scene: Scene, depth: number): Color',
                    '    -getNaturalColor(thing: Thing, pos: Vector, norm: Vector, rd: Vector, scene: Scene): any',
                    '    +render(scene: any, ctx: any, screenWidth: any, screenHeight: any): void',
                    '}',
                    '+defaultScene(): Scene',
                    '+exec(): void',
                    'Ray --> "1" Vector',
                    'Intersection --> "1" Thing',
                    'Intersection --> "1" Ray',
                    'Surface --> "1" Vector',
                    'Surface --> "1" Color',
                    'Thing --> "1" Ray',
                    'Thing --> "1" Intersection',
                    'Thing --> "1" Vector',
                    'Thing --> "1" Surface',
                    'Light --> "1" Vector',
                    'Light --> "1" Color',
                    'Camera --> "1" Vector',
                    'Scene --> "*" Thing',
                    'Scene --> "*" Light',
                    'Scene --> "1" Camera',
                    'Plane --> "1" Vector',
                    'Plane --> "1" Ray',
                    'Plane --> "1" Intersection',
                    'Plane --> "1" Surface',
                    'Sphere --> "1" Vector',
                    'Sphere --> "1" Surface',
                    'Sphere --> "1" Ray',
                    'RayTracer --> "1" Ray',
                    'RayTracer --> "1" Scene',
                    'RayTracer --> "1" Intersection',
                    'RayTracer --> "1" Color',
                    'RayTracer --> "1" Thing',
                    'RayTracer --> "1" Vector',
                    '@enduml'].join(os.EOL));
    });

    it('generate PlantUML for Generics/Complex.ts with associations', () => {
        expect(tplant.convertToPlant(tplant.generateDocumentation(['test/Playground/Generics/Complex.ts']), { associations: true, onlyInterfaces: false, onlyClasses: false }))
            .toEqual(
                ['@startuml',
                    'interface GenericInterface<T extends string> {',
                    '    +method(arg: T): T',
                    '}',
                    'interface GenericInterface2<T extends string> {',
                    '    +property?: T',
                    '}',
                    'interface GenericInterface3<T extends string, A extends number> extends GenericInterface2 {',
                    '    +method2(arg: A): A',
                    '}',
                    'class GenericClass<T extends string, A extends number> implements GenericInterface, GenericInterface3 {',
                    '    +property?: T',
                    '    +method(arg: T): T',
                    '    +method2(arg: A): A',
                    '}',
                    'class GenericClass2<T extends string> implements GenericInterface2 {',
                    '    +property?: T',
                    '}',
                    'class ConcreteClass extends GenericClass implements GenericInterface, GenericInterface2 {',
                    '    +property: string',
                    '}',
                    'interface GenericTypes {',
                    '    +genericType: GenericClass<string, number>',
                    '    +genericType2: GenericClass2<string>',
                    '    +genericReturnType(): GenericInterface<string>',
                    '    +genericReturnType2(): GenericInterface3<string, number>',
                    '    +genericParameter(parameter: GenericInterface2<string>): void',
                    '}',
                    'GenericTypes --> "1" GenericClass',
                    'GenericTypes --> "1" GenericClass2',
                    'GenericTypes --> "1" GenericInterface',
                    'GenericTypes --> "1" GenericInterface3',
                    'GenericTypes --> "1" GenericInterface2',
                    '@enduml'].join(os.EOL));
    });

    it('generate PlantUML for Generics/RecursiveGenericType.ts with associations', () => {
        expect(tplant.convertToPlant(tplant.generateDocumentation(['test/Playground/Generics/RecursiveGenericType.ts']), { associations: true, onlyInterfaces: false, onlyClasses: false }))
            .toEqual(
                ['@startuml',
                    'interface FirstGeneric<T> {',
                    '    +index: T',
                    '}',
                    'interface SecondGeneric<T> {',
                    '    +index: T',
                    '}',
                    'interface ThirdGeneric<T> {',
                    '    +index: T',
                    '}',
                    'interface NormalInterface {',
                    '    +index: any',
                    '}',
                    'interface NormalInterface_2 {',
                    '    +index: any',
                    '}',
                    'interface RecursiveGenericType {',
                    '    +recursiveGenericType: string | number | FirstGeneric<SecondGeneric<ThirdGeneric<NormalInterface> | NormalInterface_2>>',
                    '}',
                    'RecursiveGenericType --> "1" FirstGeneric',
                    'RecursiveGenericType --> "1" SecondGeneric',
                    'RecursiveGenericType --> "1" ThirdGeneric',
                    'RecursiveGenericType --> "1" NormalInterface',
                    'RecursiveGenericType --> "1" NormalInterface_2',
                    '@enduml'].join(os.EOL));
    });

    it('generate PlantUML for RayTracer with associations and only Interfaces', () => {
        expect(tplant.convertToPlant(tplant.generateDocumentation(['test/Playground/RayTracer/index.ts']), { associations: true, onlyInterfaces: true, onlyClasses: false }))
            .toEqual(
                ['@startuml',
                    'interface Ray {',
                    '    +start: Vector',
                    '    +dir: Vector',
                    '}',
                    'interface Intersection {',
                    '    +thing: Thing',
                    '    +ray: Ray',
                    '    +dist: number',
                    '}',
                    'interface Surface {',
                    '    +diffuse: (pos: Vector) => Color',
                    '    +specular: (pos: Vector) => Color',
                    '    +reflect: (pos: Vector) => number',
                    '    +roughness: number',
                    '}',
                    'interface Thing {',
                    '    +intersect: (ray: Ray) => Intersection',
                    '    +normal: (pos: Vector) => Vector',
                    '    +surface: Surface',
                    '    +destroy(): void',
                    '    +destroy(name: string): void',
                    '}',
                    'interface Light {',
                    '    +pos: Vector',
                    '    +color: Color',
                    '}',
                    'interface Scene {',
                    '    +things: Thing[]',
                    '    +lights: Light[]',
                    '    +camera: Camera',
                    '}',
                    'Intersection --> "1" Thing',
                    'Intersection --> "1" Ray',
                    'Thing --> "1" Ray',
                    'Thing --> "1" Intersection',
                    'Thing --> "1" Surface',
                    'Scene --> "*" Thing',
                    'Scene --> "*" Light',
                    '@enduml'].join(os.EOL));
    });

});
