language: node_js

node_js:
  - "node"
  - "lts/*"

before_script:
  - REPO_VERSION="$(npx -c 'echo "$npm_package_version"')"
  - echo "REPO_VERSION=$REPO_VERSION"
  - npm run lint

before_deploy:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      git tag -a -f "$REPO_VERSION"
      echo "New Tag $(git describe --tags)";
    fi

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: "tplant@tplant.com"
    api_key: $NPM_API_KEY
    on:
      tags: true
