language: node_js

node_js:
  - "node"
  - "lts/*"
  
  before_script:
    - REPO_VERSION="$(npx -c 'echo "$npm_package_version"')"
    - echo "REPO_VERSION=$REPO_VERSION"
    - TPLANT_VERSION="$(node dist/index.js -V)"
    - echo "TPLANT_VERSION=$TPLANT_VERSION"
    - NPM_PACKAGE_VERSION="$(npx tplant -v)"
    - echo "NPM_PACKAGE_VERSION=$NPM_PACKAGE_VERSION"
    - echo "TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
    - |
      if [ "$REPO_VERSION" != "$TPLANT_VERSION" ] || {[ "$TRAVIS_PULL_REQUEST_BRANCH" == "master" ] && [ "$REPO_VERSION" == "$NPM_PACKAGE_VERSION" ]}; then
        echo '\033[0;31mPackage version and commander version must be the same.'
        travis_terminate 1;
      fi
    - npm run lint
    
    before_deploy:
      - |
        if [ "$TRAVIS_BRANCH" == "master" ]; then
          git tag -a -f "$REPO_VERSION"
          echo "New Tag $(git describe --tags)";
        fi
      
      deploy:
        - provider: releases
        api_key: $GITHUB_TOKEN
        on:
          branch: master
          - provider: npm
          email: "brian.folts@gmail.com"
          api_key: $NPM_API_KEY
          on:
            tags: true